export const GET_INTERNSHIP_LOADIING = "GET_INTERNSHIP_LOADIING"
export const GET_INTERNSHIP_SUCCESS = "GET_INTERNSHIP_SUCCESS"
export const GET_INTERNSHIP_ERROR = "GET_INTERNSHIP_ERROR"

export const POST_INTERNSHIP_LOADIING = "POST_INTERNSHIP_LOADIING"
export const POST_INTERNSHIP_SUCCESS = "POST_INTERNSHIP_SUCCESS"
export const POST_INTERNSHIP_ERROR = "POST_INTERNSHIP_ERROR"

export const PATCH_INTERNSHIP_LOADIING = "PATCH_INTERNSHIP_LOADIING"
export const PATCH_INTERNSHIP_SUCCESS = "PATCH_INTERNSHIP_SUCCESS"
export const PATCH_INTERNSHIP_ERROR = "PATCH_INTERNSHIP_ERROR"

export const DELETE_INTERNSHIP_LOADIING = "DELETE_INTERNSHIP_LOADIING"
export const DELETE_INTERNSHIP_SUCCESS = "DELETE_INTERNSHIP_SUCCESS"
export const DELETE_INTERNSHIP_ERROR = "DELETE_INTERNSHIP_ERROR"