export const GET_PROFILE_LOADIING = "GET_PROFILE_LOADIING"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR"

export const POST_PROFILE_LOADIING = "POST_PROFILE_LOADIING"
export const POST_PROFILE_SUCCESS = "POST_PROFILE_SUCCESS"
export const POST_PROFILE_ERROR = "POST_PROFILE_ERROR"