export const SIGNUP_STUDENT_LOADING = "SIGNUP_LOADING"
export const SIGNUP_STUDENT_SUCCESS = "SIGNUP_STUDENT_SUCCESS"
export const SIGNUP_STUDENT_ERROR = "SIGNUP_ERROR"


export const LOGIN_STUDENT_LOADING = "LOGIN_STUDENT_LOADING"
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_SUCCESS"
export const LOGIN_STUDENT_ERROR = "LOGIN_STUDENT_ERROR"