export const SIGNUP_STUDENT_LOADING = "SIGNUP_LOADING"
export const SIGNUP_STUDENT_SUCCESS = "SIGNUP_STUDENT_SUCCESS"
export const SIGNUP_STUDENT_ERROR = "SIGNUP_ERROR"

export const SIGNUP_GET_LOADING = "SIGNUP_GET_LOADING"
export const SIGNUP_GET_SUCCESS = "SIGNUP_GET_SUCCESS"
export const SIGNUP_GET_ERROR = "SIGNUP_GET_ERROR"
export const SIGNUP_UPDATE_SUCCESS = "SIGNUP_UPDATE_SUCCESS"


export const LOGIN_STUDENT_LOADING = "LOGIN_STUDENT_LOADING"
export const LOGIN_STUDENT_SUCCESS = "LOGIN_STUDENT_SUCCESS"
export const LOGIN_STUDENT_ERROR = "LOGIN_STUDENT_ERROR"