// <=======================education action type=====================>

export const GET_EDUCATION_LOADING = "GET_EDUCATION_LOADING"
export const GET_EDUCATION_SUCCESS = "GET_EDUCATION_SUCCESS"
export const GET_EDUCATION_ERROR =   "GET_EDUCATION_ERROR"

export const CREATE_EDUCATION_LOADING = "CREATE_EDUCATION_LOADING"
export const CREATE_EDUCATION_SUCCESS = "CREATE_EDUCATION_SUCCESS"
export const CREATE_EDUCATION_ERROR = "CREATE_EDUCATION_ERROR"

export const UPDATE_EDUCATION_LOADING = "UPDATE_EDUCATION_LOADING"
export const UPDATE_EDUCATION_SUCCESS = "UPDATE_EDUCATION_SUCCESS"
export const UPDATE_EDUCATION_ERROR = "UPDATE_EDUCATION_ERROR"

export const DELETE_EDUCATION_LOADING = "DELETE_EDUCATION_LOADING"
export const DELETE_EDUCATION_SUCCESS = "DELETE_EDUCATION_SUCCESS"
export const DELETE_EDUCATION_ERROR = "DELETE_EDUCATION_ERROR"


// <=======================experience action type=====================>


export const GET_EXPERIENCE_LOADING = "GET_EXPERIENCE_LOADING"
export const GET_EXPERIENCE_SUCCESS = "GET_EXPERIENCE_SUCCESS"
export const GET_EXPERIENCE_ERROR =   "GET_EXPERIENCE_ERROR"

export const CREATE_EXPERIENCE_LOADING = "CREATE_EXPERIENCE_LOADING"
export const CREATE_EXPERIENCE_SUCCESS = "CREATE_EXPERIENCE_SUCCESS"
export const CREATE_EXPERIENCE_ERROR = "CREATE_EXPERIENCE_ERROR"

export const UPDATE_EXPERIENCE_LOADING = "UPDATE_EXPERIENCE_LOADING"
export const UPDATE_EXPERIENCE_SUCCESS = "UPDATE_EXPERIENCE_SUCCESS"
export const UPDATE_EXPERIENCE_ERROR = "UPDATE_EXPERIENCE_ERROR"

export const DELETE_EXPERIENCE_LOADING = "DELETE_EXPERIENCE_LOADING"
export const DELETE_EXPERIENCE_SUCCESS = "DELETE_EXPERIENCE_SUCCESS"
export const DELETE_EXPERIENCE_ERROR = "DELETE_EXPERIENCE_ERROR"

