export const REGISTER_COMPANY_LOADIING = "REGISTER_COMPANY_LOADIING"
export const REGISTER_COMPANY_SUCCESS = "REGISTER_COMPANY_SUCCESS"
export const REGISTER_COMPANY_ERROR = "REGISTER_COMPANY_ERROR"

export const LOGIN_CONPANY_LOADING = "LOGIN_CONPANY_LOADING"; 
export const LOGIN_CONPANY_SUCCESS = "LOGIN_CONPANY_SUCCESS"; 
export const LOGIN_CONPANY_ERROR = "LOGIN_CONPANY_ERROR"; 